"""Initial schema for scans and findings

Revision ID: 19efe4099d72
Revises: 
Create Date: 2025-04-24 14:27:29.815962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19efe4099d72'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aws_account_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='scanstatus'), nullable=False),
    sa.Column('scan_type', sa.Enum('QUICK', 'STANDARD', 'COMPREHENSIVE', name='scantype'), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('regions_scanned', sa.JSON(), nullable=True),
    sa.Column('services_scanned', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_aws_account_id'), 'scans', ['aws_account_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFORMATIONAL', name='findingseverity'), nullable=False),
    sa.Column('category', sa.Enum('IAM', 'PUBLIC_EXPOSURE', 'ENCRYPTION', 'NETWORK', 'COMPLIANCE', 'OTHER', name='findingcategory'), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remediation_steps', sa.JSON(), nullable=True),
    sa.Column('compliance_standards', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_account_id'), 'findings', ['account_id'], unique=False)
    op.create_index(op.f('ix_findings_category'), 'findings', ['category'], unique=False)
    op.create_index(op.f('ix_findings_region'), 'findings', ['region'], unique=False)
    op.create_index(op.f('ix_findings_resource_id'), 'findings', ['resource_id'], unique=False)
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_index(op.f('ix_findings_resource_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_region'), table_name='findings')
    op.drop_index(op.f('ix_findings_category'), table_name='findings')
    op.drop_index(op.f('ix_findings_account_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_scans_aws_account_id'), table_name='scans')
    op.drop_table('scans')
    # ### end Alembic commands ###
